application: gu-byline-data
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /api/twitter/.*
  script: twitter.app
- url: /admin/.*
  login: admin
  script: admin.app
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest